### PR TITLE
Add test for GH #408 PackageRecord error

### PR DESCRIPTION
**Pull request by maresb**
I'm not sure what's causing #408 but I want to write a test so we can check when it's solved.

### CODE REVIEW

**Comment by ogrisel** [comment]
I recently observed the `KeyError` for the `__osx` package when running a conda-lock with recent mamba & conda installed on my system.

I contributed a fix to the upstream repo that works for me:

- https://github.com/mamba-org/mamba/pull/2923

I am not sure if this is related to this or not.

/cc @lesteve.

**Comment by maresb** [comment]
Ah, bad news, but thanks for letting us know. Also thanks for submitting the upstream fix! And also for raising visibility on this PR which I meant to merge.

**Comment by maresb** [comment]
@ogrisel, can you share your `environment.yml` file which led to the error?

**Comment by ogrisel** [comment]
```
conda-lock lock --mamba --kind explicit --platform osx-64 --file build_tools/azure/pylatest_conda_forge_mkl_osx-64_environment.yml --filename-template build_tools/azure/pylatest_conda_forge_mkl_osx-64_conda.lock
```

and here is the content of `pylatest_conda_forge_mkl_osx-64_environment.yml`:

```yaml
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - blas[build=mkl]
  - scipy
  - cython
  - joblib
  - threadpoolctl
  - matplotlib
  - pandas
  - pyamg
  - pytest
  - pytest-xdist=2.5.0
  - pillow
  - setuptools
  - pytest-cov
  - coverage
  - ccache
  - compilers
  - llvm-openmp
```

**Comment by lesteve** [comment]
For the record this command runs fine for me on a Linux machine, so maybe the issue only happens when running the command on an OSX machine?

**Comment by ogrisel** [comment]
Yes I believe that this might be because the `__osx` virtual package does not show up on a Linux host.

This is probably a bug of mamba or conda that ignores the `--platform osx-64` argument when defining the system specific virtual packages.

**Pull request merged**
