### PR TITLE
[WIP] Update to poetry 1.8.2 (minimal changes)

### PR DESCRIPTION
**Pull request by romain-intel**
### Description

This addresses #613 and updates Poetry to a more modern release (in particular taking in changes around support for Metadata from pypi indices).

This is still a WIP, still missing:
  - proper setup for the environment (needs support for environment markers to properly resolve cross platform)
  - fix the failing tests (hash override) -- I am not sure if this is still relevant as well so not 100% sure how to proceed here.
  - verification of the small code changes that were done to support the new APIs
Putting it out here so people can take a look and see if there is anything that should be addressed first.

### CODE REVIEW

**Comment by maresb** [comment]
Thanks a lot for this!!! Did you use the `vendoring` tool? If so, are you leaving the source code inside the `conda_lock/_vendor` directly untouched?

When you're ready for more serious review, would it be possible to put `vendoring sync` in its own commit?

**Comment by romain-intel** [comment]
I did use vendoring sync. I ran it and fixed up the issues in the other files (the API changes a bit). I think there was one change after the vendoring tool. I'll update the patch to fix it up (it was just hardcoding a version value). But otherwise yes, there is *no* other change than the ones made by the vendoring tool. 

Are you saying you just want the broken commit (ie: it won't work) separately from the fixes so that it is easier to review just the "changes"?

**Comment by maresb** [comment]
> Are you saying you just want the broken commit (ie: it won't work) separately from the fixes so that it is easier to review just the "changes"?

Exactly, that would be excellent! Probably a more direct way to phrase it is that I'd like a single commit that runs `vendoring sync` with absolutely no other changes. Please feel free to use `git commit --no-verify`. That should make it significantly easier for me to review. Thanks!!!

**Comment by romain-intel** [comment]
Closed in favor of #637 which refactors the commits.

**Comment by maresb** [comment]
Looks like this wasn't actually closed, but that seems to have been your intention based on the last comment. (I'll leave it to you.)

**Pull request closed without merging**
