### PR TITLE
Store lockfile-relative sources in lockfiles

### PR DESCRIPTION
**Pull request by riccardoporreca**
### Description

This is the revised fix for #229 following the original PR #230, especially given what done in #204 for the inputs metadata.

In fact, we use consistently what introduced in #204 for the actual `metadata.sources` in the lockfile, where lockfile-relative paths are always used (as the most sensible approach) unless this is made impossible by paths being on different drives, thus addressing the needs of #175, in a ways even more specific than what originally though in [#228](https://github.com/conda/conda-lock/issues/229#issuecomment-1209933411)

### CODE REVIEW

**Comment by riccardoporreca** [comment]
I introduced a test for the lockfile-relative sources. I am not sure how we can test the case where paths are on different drives, which is now the only case when absolute paths are stored. Happy to take any suggestion, perhaps mocking `conda_lock.common.relative_path` to raise the exception thus forcing the behavior?

**Comment by riccardoporreca** [comment]
There is an issue with the pre-commit, which I also had locally and seems completely unrelated

**Comment by riccardoporreca** [comment]
There is also a failing `test_run_lock_regression_gh155[micromamba]` (on Python 3.8 only), which seems pretty unrelated as it should be very specific to #155

**Comment by maresb** [comment]
Ya, the precommit failure is related to a bad release of isort, and is fixed by #327. For the CI failures they are random and I am rerunning the failed tests. I am trying to track down the root cause but unfortunately my time is very limited over the next few weeks.

**Comment by riccardoporreca** [comment]
@maresb, I noticed the merge fro `main` has also included dropping support for python < 3.8 (#330).

There are just a few conditions like  `if sys.version_info < (3, 8)` in `test_conda_lock.py`, one of which is part of the test I introduced in the PR: I am happy to clean this up if you agree, otherwise it might be worth a second PR after this one is merged

**Comment by maresb** [comment]
Ya, I think it's fine to wait, especially since the cases you mention are so clearly marked. If someone comes along with an objection before the next release I am open to reverting #330, so I am glad to retain 3.6 compatibility for now.

At some point we should modernize the coding style, like by adding pyupgrade as a pre-commit hook. But before that I am hoping that we can wind down the review queue enough in order to avoid creating nasty merge conflicts for the current contributors.

**Review by maresb — APPROVED** [review]
Thanks a lot for your patience and persistence on this. @mariusvniekerk, could you please take a look?

**Review by mariusvniekerk — APPROVED** [review]

**Comment by maresb** [comment]
Thank you @riccardoporreca!!!

**Pull request merged**
