### PR TITLE
Consistent lockfile-relative vs absolute sources

### LINKED ISSUE #229: Allow relative paths for sources
Since #189, paths stored in the lockfile are stored as absolute, to address the issue in #175 where the lockfile and the sources are not on the same drive.

However, there was probably a point in relative paths and the change has its drawback for other (more common?). Consider sources and lockfiles maintained under version control in the same repo: one wouldn't want to produce and push lockfiles containing references to the absolute path of the local checkout.

I think using absolute paths should be opt-in, or used in case the construction of relative paths does not work.

### PR DESCRIPTION
**Pull request by riccardoporreca**
Resolve #229

### CODE REVIEW

**Comment by riccardoporreca** [comment]
On hold waiting for PR #204, see https://github.com/conda-incubator/conda-lock/pull/204#discussion_r943911165

**Comment by bstadlbauer** [comment]
@riccardoporreca @maresb I think #204 would be merged - anything I could help with here?

**Comment by maresb** [comment]
Looks like there are merge conflicts to be resolved

**Comment by maresb** [comment]
@bstadlbauer, you could rebase @riccardoporreca's branch on `main` and open a new PR referencing this one.

**Comment by riccardoporreca** [comment]
@bstadlbauer, @maresb, if this can wait till the weekend, I will be happy to take care of the rebasing

**Comment by bstadlbauer** [comment]
@riccardoporreca Could we add a test that checks the new behavior? Just to make sure there is no regression in future versions

**Comment by srilman** [comment]
@riccardoporreca Is it alright to add the missing tests for you? Ran into this issue recently and would love to see this PR merged.

**Comment by riccardoporreca** [comment]
@maresb, @bstadlbauer, I was too optimistic with my time before the festivities in December :), thanks  @srilman for the reminder.

I will manage to rebase and at least draft some tests in the next few days

**Comment by riccardoporreca** [comment]
See #328 for the rebased/revamped PR

**Pull request closed without merging**
